### ISSUE TITLE
Split 3D Object Export Not Working

### ISSUE THREAD

**Issue by OffensiveLemon** [RaduMC/UnityStudio#34]
When I try to export Besiege's model data by hitting "Export" -> "All 3D objects (Split)," the program crashes, regardless of how much stuff I have in the hierarchy.  For example:
![image](https://user-images.githubusercontent.com/31805871/30243239-76669474-9573-11e7-9389-12ca387436be.png)
![image](https://user-images.githubusercontent.com/31805871/30243243-8ab070b2-9573-11e7-86d5-90d61cce4e2d.png)
![image](https://user-images.githubusercontent.com/31805871/30243245-a7ef79a2-9573-11e7-88e9-023162fd72c4.png)
![image](https://user-images.githubusercontent.com/31805871/30243248-b3d862d8-9573-11e7-96a7-71302f59c020.png)
![image](https://user-images.githubusercontent.com/31805871/30243253-c59bd45a-9573-11e7-9bcf-56225e514d53.png)
The same thing happens when I export all assets, but that's probably because there are a LOT of assets.

**Comment by andangel** [comment]
metoo

**Comment by Mactastic1-5** [comment]
Use https://github.com/Perfare/UnityStudio instead. It is more stable and is still being maintained.

**Comment by OffensiveLemon** [comment]
Wait, I just realized that's what I've been using the whole time.  Damn those forks.  Issue still not solved, I'm moving it over to the other one.
