### ISSUE TITLE
Life is Strange Before the Storm Eye Issue

### ISSUE THREAD

**Issue by Lilothestitch16** [RaduMC/UnityStudio#35]
When I Extract the models from Life is Strange Before the Storm, their eyes look so weird.
![chloe price life is strange before the storm](https://user-images.githubusercontent.com/8963276/30244253-ca822996-9588-11e7-85ff-f437cef48a7e.png)

**Comment by Mactastic1-5** [comment]
Try using https://github.com/Perfare/UnityStudio instead, close this post and make a post on that repository. This repository is no longer being maintained.

**Comment by Lilothestitch16** [comment]
I already posted there.
