### ISSUE TITLE
Can't open bundles files 000.unity3d

### ISSUE THREAD

**Issue by Sn0wBiT** [RaduMC/UnityStudio#4]
I'm trying to extract these bundles files, but Unity Studio seems like didn't recognize them.
![image](https://cloud.githubusercontent.com/assets/9019527/13104426/a1311c06-d58f-11e5-980a-8a8f33c2da77.png)

**Comment by Mactastic1-5** [comment]
@SowBiT There are several other programs you can try such as [Disunity](https://github.com/Stellarspace/disunity). You won't be able to extract the .assets with v0.5.x because it doesn't support object deserialization.
